"""Capsule save/reload.

Ships a real ``.lxp/`` directory format that satisfies the Phase 2 gate
("portable, inspectable, reloadable, exportable"). The writer here is the
single producer of capsule artifacts and is responsible for wiring in
every Phase 2 subsystem:

* Phase 2A — canonical ``manifest.toml`` (Pydantic ``Manifest``) and HDF5
  ``results/diagnostics.h5``. JSON is kept as a sidecar for legacy tools.
* Phase 2B — full provenance triad: ``ProvenanceLock`` (TOML) +
  ``environment.yaml`` (pip freeze + system info) + append-only
  ``agent_trace.md`` (``AgentTraceWriter``).
* Phase 2C — the saved capsule is the input to ``export_capsule`` and
  ``fork_capsule``; both rely on this writer's structural output.

Carries ``agent_error_patterns.md`` "Building writers without wiring
producers" — every Phase 2B writer MUST be invoked from this function.

Layout (plan §7.1):

    <name>.lxp/
      manifest.toml             — capsule metadata + format version (v0.1)
      model/model_spec.yaml     — copy of the experiment's ModelSpec
      configs/run_config.yaml   — Experiment + RunConfig + BackendConfig
      results/
        diagnostics.h5          — canonical bulk data (Phase 2A, ADR-0002)
        diagnostics.json        — sidecar for non-HDF5 readers
      provenance/
        provenance.lock         — Phase 2B ProvenanceLock (TOML)
        environment.yaml        — Phase 2B capture_environment()
        agent_trace.md          — Phase 2B AgentTraceWriter (append-only)
      paper_sources/, src/{generated,user_edits,kernels}/, data/,
      validation/, notebooks/   — created empty with .gitkeep markers
      README.md                 — autogenerated capsule summary
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from simworkbench import __version__ as workbench_version
from simworkbench.experiment import Experiment
from simworkbench.model_spec import to_dict as model_spec_to_dict
from simworkbench.paths import is_under_workbench, simulation_capsules_root
from simworkbench.runtime.runner import RunResult

CAPSULE_FORMAT_VERSION = "0.1"


@dataclass
class LoadedCapsule:
    """Parsed capsule + the run result it carries.

    Phase 1 keeps this lightweight: the experiment is reconstructable, the
    diagnostics are returned as plain dicts. Phase 2 will add a richer
    handle with capsule-level operations (fork, export, validate).
    """

    path: Path
    name: str
    format_version: str
    experiment: Experiment
    diagnostics: dict[str, list[float]]
    placeholders: list[str]
    final_simulation_time: float
    state: str
    elapsed_seconds: float
    provenance: dict[str, Any]


# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------


def save_capsule(
    *,
    experiment: Experiment,
    result: RunResult,
    name: str | None = None,
    base: Path | None = None,
) -> Path:
    """Write a capsule for ``experiment`` + ``result``. Return its directory.

    Validates the target path is under the four allowed workbench roots
    BEFORE creating any directories — honors `agent_error_patterns.md`
    "Side-effecting before validating".
    """
    capsule_name = name or _default_capsule_name(experiment, result)
    if not capsule_name.endswith(".lxp"):
        capsule_name = f"{capsule_name}.lxp"
    if base is None:
        base = simulation_capsules_root()
    target = Path(base) / capsule_name

    # Validate first; only then create.
    if not is_under_workbench(target):
        raise PermissionError(
            f"Refusing to save capsule outside workbench-managed roots: {target}"
        )
    target.mkdir(parents=True, exist_ok=True)

    # Manifest — Phase 2A canonical schema (Pydantic Manifest model).
    from simworkbench.serialization.manifest import (
        CapsuleSection,
        Manifest,
        ModelSection,
        RuntimeSection,
        write_manifest,
    )

    manifest = Manifest(
        capsule=CapsuleSection(
            name=capsule_name.removesuffix(".lxp"),
            format_version=CAPSULE_FORMAT_VERSION,
            workbench_version=workbench_version,
            created_at=_utc_now_iso(),
        ),
        model=ModelSection(
            name=experiment.model_spec.model.name,
            domain=experiment.model_spec.model.domain,
            schema_version=experiment.model_spec.schema_version,
        ),
        runtime=RuntimeSection(
            backend=experiment.backend_config.name,
            default_seed=experiment.run_config.seed,
            final_state=result.state.value,
            final_simulation_time_seconds=result.final_simulation_time,
            elapsed_seconds=result.elapsed_seconds,
            placeholder_used=bool(result.placeholders),
            placeholders=list(result.placeholders),
        ),
    )
    write_manifest(manifest, target / "manifest.toml")

    # Model spec.
    (target / "model").mkdir(parents=True, exist_ok=True)
    (target / "model" / "model_spec.yaml").write_text(
        yaml.safe_dump(model_spec_to_dict(experiment.model_spec), sort_keys=False, indent=2),
        encoding="utf-8",
    )

    # Run / backend / diagnostic config.
    (target / "configs").mkdir(parents=True, exist_ok=True)
    (target / "configs" / "run_config.yaml").write_text(
        yaml.safe_dump(experiment.to_dict(), sort_keys=False, indent=2),
        encoding="utf-8",
    )

    # Results — JSON in Phase 1; HDF5/Zarr in Phase 2 per ADR-0002.
    (target / "results").mkdir(parents=True, exist_ok=True)
    (target / "results" / "diagnostics.json").write_text(
        json.dumps(
            {
                "run_id": result.run_id,
                "state": result.state.value,
                "elapsed_seconds": result.elapsed_seconds,
                "final_simulation_time": result.final_simulation_time,
                "diagnostics": {k: list(v) for k, v in result.diagnostics.items()},
                "placeholders": list(result.placeholders),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    # HDF5 sidecar for the same diagnostics — Phase 2A authoritative bulk
    # format per ADR-0002 (Accepted). The JSON above is preserved for
    # tools that don't read HDF5.
    from simworkbench.serialization.bulk_data import write_diagnostics_h5

    write_diagnostics_h5(
        result.diagnostics,
        target / "results" / "diagnostics.h5",
        metadata={
            "run_id": result.run_id,
            "state": result.state.value,
            "elapsed_seconds": result.elapsed_seconds,
            "final_simulation_time_seconds": result.final_simulation_time,
            "placeholder_used": bool(result.placeholders),
            # Persist the full placeholder list, not just the boolean.
            # Carries `agent_error_patterns.md` "Serializer drops
            # semantic fields when writing the canonical format" — an
            # HDF5-only capsule reload had been losing the names.
            "placeholders": list(result.placeholders),
        },
    )

    # Phase 2B provenance triad — `provenance.lock` (TOML) + environment.yaml
    # (pip freeze + system) + `agent_trace.md` (append-only). Honors
    # `agent_error_patterns.md` "Building writers without wiring producers":
    # the producer (this function) MUST invoke every Phase 2B writer; if
    # someone adds a new triad member, this is the call site that picks it up.
    import platform as _platform
    import sys as _sys

    from simworkbench.provenance import (
        AgentTraceWriter,
        ProvenanceLock,
        write_environment,
        write_lock,
    )
    from simworkbench.provenance.sources import SourceRegistry

    (target / "provenance").mkdir(parents=True, exist_ok=True)
    # Empty the empty subtrees BEFORE hashing so the source-aggregate hash is
    # stable across saves of the same content (the .gitkeep files are part of
    # the capsule identity).
    for empty in (
        "paper_sources",
        "src/generated",
        "src/user_edits",
        "src/kernels",
        "data",
        "validation",
        "notebooks",
    ):
        (target / empty).mkdir(parents=True, exist_ok=True)
        (target / empty / ".gitkeep").touch()

    model_spec_hash = SourceRegistry(target).aggregate_hash(subtrees=("model",))
    lock = ProvenanceLock(
        workbench_version=workbench_version,
        python_version=_sys.version.split()[0],
        platform=_platform.platform(),
        capsule_format_version=CAPSULE_FORMAT_VERSION,
        run_id=result.run_id,
        base_seed=experiment.run_config.seed,
        backend=experiment.backend_config.name,
        model_spec_hash=model_spec_hash,
        placeholders=list(result.placeholders),
        parent_capsule_hash="",
        created_at=_utc_now_iso(),
    )
    write_lock(lock, target / "provenance" / "provenance.lock")
    write_environment(target / "provenance" / "environment.yaml")

    # Append-only agent_trace.md — `AgentTraceWriter` initializes the file
    # with the header on first call and appends one entry per save. Re-saving
    # the same capsule appends a new entry rather than overwriting (carries
    # `agent_error_patterns.md` "Append-only files written non-appendingly").
    trace = AgentTraceWriter(target / "provenance" / "agent_trace.md")
    trace.append(
        agent="simworkbench.serialization.capsule.save_capsule",
        action="saved capsule",
        files_touched=("manifest.toml", "results/diagnostics.h5"),
        notes=(
            f"workbench={workbench_version} format={CAPSULE_FORMAT_VERSION} "
            f"run_id={result.run_id} backend={experiment.backend_config.name}"
        ),
    )

    # Top-level README.
    readme = (
        f"# {capsule_name}\n\n"
        f"Workbench capsule, format v{CAPSULE_FORMAT_VERSION} (Phase 2A schema, "
        "ADR-0002 Accepted).\n\n"
        f"- Model: `{experiment.model_spec.model.name}` — domain "
        f"`{experiment.model_spec.model.domain}`\n"
        f"- Backend: `{experiment.backend_config.name}`\n"
        f"- Final state: `{result.state.value}`, "
        f"t_final = {result.final_simulation_time:.6g} s\n"
        f"- Placeholder rates used: {bool(result.placeholders)}"
        f" — {list(result.placeholders)}\n\n"
        "Bulk diagnostics are at `results/diagnostics.h5` (HDF5); a JSON "
        "sidecar at `results/diagnostics.json` is preserved for non-HDF5 tools.\n"
    )
    (target / "README.md").write_text(readme, encoding="utf-8")

    return target


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------


def load_capsule(path: str | Path) -> LoadedCapsule:
    """Read a capsule directory and return a ``LoadedCapsule``."""
    capsule_dir = Path(path).resolve()
    if not capsule_dir.is_dir():
        raise FileNotFoundError(f"Capsule directory not found: {capsule_dir}")

    manifest_path = capsule_dir / "manifest.toml"
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"No manifest.toml under {capsule_dir}; not a capsule directory."
        )
    manifest = _read_toml(manifest_path)

    capsule_section = manifest.get("capsule", {})
    fmt_version = capsule_section.get("format_version", "0.0")
    if fmt_version != CAPSULE_FORMAT_VERSION:
        raise ValueError(
            f"Unsupported capsule format_version {fmt_version!r}; "
            f"this build understands {CAPSULE_FORMAT_VERSION!r}. "
            "Capsule migrations land in Phase 2."
        )

    # Experiment lives at configs/run_config.yaml (it serializes the full
    # Experiment, ModelSpec inlined, by design of Workstream 1A).
    run_config_path = capsule_dir / "configs" / "run_config.yaml"
    if not run_config_path.is_file():
        raise FileNotFoundError(f"No configs/run_config.yaml under {capsule_dir}.")
    experiment = Experiment.load_yaml(run_config_path)

    # Diagnostics — HDF5 is canonical (Phase 2A); JSON sidecar is the
    # fallback for legacy or partial capsules. We read scalar metadata
    # (run_id, state, elapsed_seconds, final_simulation_time, placeholders)
    # from the JSON sidecar when available so the LoadedCapsule shape stays
    # complete regardless of which path was canonical.
    h5_path = capsule_dir / "results" / "diagnostics.h5"
    json_path = capsule_dir / "results" / "diagnostics.json"
    diagnostics: dict[str, list[float]] = {}
    payload: dict[str, Any] = {}
    if h5_path.is_file():
        from simworkbench.serialization.bulk_data import read_diagnostics_h5

        h5_data, h5_meta = read_diagnostics_h5(h5_path)
        diagnostics = {k: v.tolist() for k, v in h5_data.items()}
        payload.update(h5_meta)
        # ``placeholders`` is stored as a vlen-string list in HDF5; the
        # reader returns ``list[str]``. We coerce empty-string elements
        # away to keep the contract clean (an empty token list reads
        # back as ``[]`` rather than ``[""]``).
        if "placeholders" in payload and isinstance(payload["placeholders"], list):
            payload["placeholders"] = [
                str(p) for p in payload["placeholders"] if p
            ]
    if json_path.is_file():
        json_payload = json.loads(json_path.read_text(encoding="utf-8"))
        if not diagnostics:
            diagnostics = {
                k: list(v) for k, v in json_payload.get("diagnostics", {}).items()
            }
        # Sidecar metadata fills in scalars HDF5 didn't carry.
        for key in (
            "run_id",
            "state",
            "elapsed_seconds",
            "final_simulation_time",
            "placeholders",
        ):
            payload.setdefault(key, json_payload.get(key))
    if not h5_path.is_file() and not json_path.is_file():
        raise FileNotFoundError(
            f"No diagnostics under {capsule_dir}/results/ "
            "(expected diagnostics.h5 or diagnostics.json)."
        )

    provenance_path = capsule_dir / "provenance" / "provenance.lock"
    provenance = _read_toml(provenance_path) if provenance_path.is_file() else {}

    final_simulation_time_meta = (
        payload.get("final_simulation_time")
        if "final_simulation_time" in payload
        else payload.get("final_simulation_time_seconds", 0.0)
    )
    return LoadedCapsule(
        path=capsule_dir,
        name=capsule_section.get("name", capsule_dir.stem),
        format_version=fmt_version,
        experiment=experiment,
        diagnostics=diagnostics,
        placeholders=list(payload.get("placeholders", []) or []),
        final_simulation_time=float(final_simulation_time_meta or 0.0),
        state=str(payload.get("state") or "unknown"),
        elapsed_seconds=float(payload.get("elapsed_seconds") or 0.0),
        provenance=provenance,
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _default_capsule_name(experiment: Experiment, result: RunResult) -> str:
    base = experiment.model_spec.model.name.replace(" ", "_")
    return f"{base}-{result.run_id[:8]}"


def _utc_now_iso() -> str:
    from datetime import UTC, datetime

    return datetime.now(UTC).isoformat(timespec="microseconds")


def _read_toml(path: Path) -> dict[str, Any]:
    """Parse TOML using the stdlib ``tomllib`` (Python 3.11+)."""
    import tomllib

    with path.open("rb") as fh:
        return tomllib.load(fh)


__all__ = [
    "CAPSULE_FORMAT_VERSION",
    "LoadedCapsule",
    "load_capsule",
    "save_capsule",
]
