"""Phase 6A — Code Generation Backend.

Plan §Phase 6 / 6A enumerates six task bullets:

  1. Generate Python experiment code from ModelSpec.
  2. Generate configuration files.
  3. Generate diagnostic code.
  4. Generate tests.
  5. Generate documentation.
  6. Preserve readable structure.

The default ``CodeGenerator`` implementation is deterministic and
offline-safe — every output is a function of the input ModelSpec. An
LLM-backed generator can plug in by subclassing.

Outputs are written through the Phase 6B sandbox (see
``simworkbench.codegen.sandbox``). The sandbox refuses any write under
``user_edits/``, ``paper_sources/``, or ``provenance/`` even if the
caller asks for it, which keeps the gate-walk regression
``test_phase_6_gate_walk_regeneration_preserves_user_edits`` green.

Plan §Phase 4 hard rule continues to apply: a generated experiment is
NOT a validated simulation. The reviewer drives the validation run
(Phase 6E) and decides whether to promote.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import yaml

from simworkbench import __version__ as workbench_version
from simworkbench.experiment import Experiment, RunConfig
from simworkbench.model_spec import ModelSpec
from simworkbench.model_spec import to_dict as model_spec_to_dict

from .sandbox import SandboxViolation, sandboxed_write
from .test_generation import TestGenerator


class CodeGenerationError(RuntimeError):
    """Raised when generation preconditions fail."""


@dataclass
class CodeGenerationResult:
    """What the generator wrote.

    ``files_written`` is repo-relative-to-capsule paths in the order
    they landed; ``manifest_path`` points at ``codegen_manifest.json``
    (used by the diff endpoint). ``removed_files`` lists prior-
    generation orphans that this run cleaned up — the empty-list case
    is the fresh-generation default.
    """

    capsule: Path
    files_written: list[str] = field(default_factory=list)
    file_hashes: dict[str, str] = field(default_factory=dict)
    manifest_path: Path | None = None
    removed_files: list[str] = field(default_factory=list)


_GENERATED_HEADER = (
    "# Generated by simworkbench.codegen.CodeGenerator\n"
    "# This file lives in <capsule>/src/generated/. The reviewer's edits\n"
    "# go in <capsule>/src/user_edits/ instead — regeneration overwrites\n"
    "# this directory but never touches user_edits/.\n"
)


class CodeGenerator:
    """Deterministic ModelSpec → Python experiment renderer."""

    def generate(
        self,
        capsule_dir: str | Path,
        spec: ModelSpec,
    ) -> CodeGenerationResult:
        capsule = Path(capsule_dir)
        if not capsule.is_dir():
            raise CodeGenerationError(
                f"Capsule directory does not exist: {capsule}"
            )

        files: list[str] = []
        hashes: dict[str, str] = {}

        # Pre-load the previous manifest (if any) so we can compute a
        # real diff and clean orphans after writing the new tree.
        # Carries `agent_error_patterns.md` "Generator skips cleanup,
        # leaving stale artifacts".
        prior_manifest_path = capsule / "src" / "generated" / "codegen_manifest.json"
        prior_paths: set[str] = set()
        if prior_manifest_path.is_file():
            try:
                prior = json.loads(prior_manifest_path.read_text(encoding="utf-8"))
                prior_paths = {
                    entry["path"]
                    for entry in prior.get("files", [])
                    if isinstance(entry, dict) and "path" in entry
                }
            except Exception:  # noqa: BLE001 — corrupt prior manifest = empty diff baseline.
                prior_paths = set()

        # 1. Python experiment scaffold.
        files.append(self._write(
            capsule, "src/generated/experiment.py",
            self._render_experiment(spec), hashes,
        ))
        # 2. Configuration files.
        files.append(self._write(
            capsule, "src/generated/config.yaml",
            self._render_config(spec), hashes,
        ))
        # 3. Diagnostic code.
        files.append(self._write(
            capsule, "src/generated/diagnostics.py",
            self._render_diagnostics(spec), hashes,
        ))
        # 4. Generated tests (Phase 6C — delegate to TestGenerator).
        for relative, body in TestGenerator().render(spec).items():
            files.append(self._write(capsule, relative, body, hashes))
        # 5. Documentation.
        files.append(self._write(
            capsule, "src/generated/README.md",
            self._render_readme(spec), hashes,
        ))
        # 6. Run helper that the validation runner imports.
        files.append(self._write(
            capsule, "src/generated/run.py",
            self._render_run_helper(spec), hashes,
        ))

        # Phase 6B "track generated files": persist a manifest the diff
        # endpoint reads.
        manifest = {
            "generated_at": _utc_now_iso(),
            "workbench_version": workbench_version,
            "spec_name": spec.model.name,
            "spec_domain": spec.model.domain,
            "files": [
                {"path": p, "sha256": hashes[p]} for p in files
            ],
        }
        manifest_path = sandboxed_write(
            capsule,
            "src/generated/codegen_manifest.json",
            json.dumps(manifest, indent=2) + "\n",
        )
        files.append("src/generated/codegen_manifest.json")
        hashes["src/generated/codegen_manifest.json"] = _sha256(
            manifest_path.read_text(encoding="utf-8")
        )

        # Cleanup: remove stale files that the prior generation produced
        # but the current run did not. Sandbox-checked so user_edits/,
        # paper_sources/, provenance/ stay untouched even if the prior
        # manifest had bogus paths under those subtrees.
        current_set = set(files)
        orphans = sorted(prior_paths - current_set)
        removed: list[str] = []
        for relative in orphans:
            try:
                self._remove_under_sandbox(capsule, relative)
            except SandboxViolation:
                # Refuse to delete anything outside the generated/
                # subtree — defense in depth against a tampered
                # manifest.
                continue
            removed.append(relative)

        return CodeGenerationResult(
            capsule=capsule,
            files_written=files,
            file_hashes=hashes,
            manifest_path=manifest_path,
            removed_files=removed,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _write(
        capsule: Path,
        relative: str,
        content: str,
        hashes: dict[str, str],
    ) -> str:
        sandboxed_write(capsule, relative, content)
        hashes[relative] = _sha256(content)
        return relative

    @staticmethod
    def _remove_under_sandbox(capsule: Path, relative: str) -> None:
        """Delete a stale generated file. The path goes through the
        same allowed-roots / off-limits checks as ``sandboxed_write``
        so a tampered prior manifest cannot ask us to delete outside
        ``src/generated/`` or under user_edits/.
        """
        from .sandbox import (
            ALLOWED_GENERATED_SUBDIR,
            ALLOWED_VALIDATION_SUBDIR,
            OFF_LIMITS_SUBDIRS,
        )

        target = capsule.resolve() / Path(relative)
        target_resolved = target.resolve()
        try:
            relative_resolved = target_resolved.relative_to(capsule.resolve())
        except ValueError as exc:
            raise SandboxViolation(
                f"Refusing to delete outside the capsule: {target_resolved}"
            ) from exc
        for forbidden in OFF_LIMITS_SUBDIRS:
            try:
                relative_resolved.relative_to(forbidden)
            except ValueError:
                continue
            raise SandboxViolation(
                f"Refusing to delete under {forbidden}/: {relative_resolved}"
            )
        allowed = (ALLOWED_GENERATED_SUBDIR, ALLOWED_VALIDATION_SUBDIR)
        if not any(
            _is_under_path(relative_resolved, root) for root in allowed
        ):
            raise SandboxViolation(
                f"Refusing to delete outside generated/validation roots: "
                f"{relative_resolved}"
            )
        if target_resolved.is_file():
            target_resolved.unlink()

    @staticmethod
    def _render_experiment(spec: ModelSpec) -> str:
        species_lines = "\n".join(
            f'        "{s.name}": {{"type": {s.type!r}, "initial_density_units": "1/m^3"}},'
            for s in spec.species
        )
        return (
            _GENERATED_HEADER
            + '"""Generated experiment scaffold.\n'
            + f"\nDomain: {spec.model.domain}\nModel: {spec.model.name}\n"
            + 'Reviewer: this file is regenerated when the ModelSpec changes.\n'
            + 'Hand-edits belong in ../user_edits/ (regeneration never overwrites that tree).\n'
            + '"""\n\n'
            + "from __future__ import annotations\n\n"
            + "from pathlib import Path\n\n"
            + "from simworkbench.experiment import Experiment, RunConfig\n"
            + "from simworkbench.model_spec import load_yaml\n"
            + "from simworkbench.runtime import Runner\n\n\n"
            + "SPEC_PATH = (\n"
            + "    Path(__file__).resolve().parent.parent.parent\n"
            + "    / \"model\" / \"model_spec.yaml\"\n"
            + ")\n\n\n"
            + "SPECIES = {\n"
            + species_lines + ("\n" if species_lines else "")
            + "}\n\n\n"
            + "def build_experiment() -> Experiment:\n"
            + '    """Construct the canonical Phase-1 Experiment for this capsule."""\n'
            + "    spec = load_yaml(SPEC_PATH)\n"
            + "    return Experiment.from_model_spec(\n"
            + "        spec,\n"
            + "        run_config=RunConfig(\n"
            + '            start_time="0 s", end_time="100 ns", max_steps=50, seed=0,\n'
            + "        ),\n"
            + "    )\n\n\n"
            + 'def run() -> "tuple[Experiment, object]":\n'
            + '    """Build the experiment, run it on the python_cpu backend, return both."""\n'
            + "    experiment = build_experiment()\n"
            + "    result = Runner(experiment, base_seed=0).run()\n"
            + "    return experiment, result\n\n\n"
            + 'if __name__ == "__main__":\n'
            + "    _, result = run()\n"
            + "    print(\n"
            + '        f"final state: {result.state.value}, "\n'
            + '        f"t = {result.final_simulation_time}"\n'
            + "    )\n"
        )

    @staticmethod
    def _render_config(spec: ModelSpec) -> str:
        config = {
            "experiment": {
                "name": spec.model.name,
                "domain": spec.model.domain,
                "schema_version": spec.schema_version,
            },
            "run": {
                "start_time": "0 s",
                "end_time": "100 ns",
                "max_steps": 50,
                "seed": 0,
            },
            "backend": {
                "name": "python_cpu",
                "options": {},
            },
            "diagnostics": [
                {"name": d.name, "quantity": d.quantity}
                for d in spec.diagnostics
            ],
        }
        return (
            "# Generated by simworkbench.codegen.CodeGenerator.\n"
            "# Reviewer-editable: copy to ../user_edits/config.yaml and edit there.\n\n"
            + yaml.safe_dump(config, sort_keys=False)
        )

    @staticmethod
    def _render_diagnostics(spec: ModelSpec) -> str:
        species_dump = "\n".join(
            f'    "{s.name}",  # {s.type}'
            for s in spec.species
        )
        return (
            _GENERATED_HEADER
            + '"""Generated diagnostic helpers.\n\n'
            + "Each helper takes a Phase-1 ``RunResult`` and returns a NumPy\n"
            + "array. Reviewer extends with paper-specific diagnostics under\n"
            + "../user_edits/.\n"
            + '"""\n\n'
            + "from __future__ import annotations\n\n"
            + "import numpy as np\n\n\n"
            + "TRACKED_SPECIES = [\n"
            + species_dump + ("\n" if species_dump else "")
            + "]\n\n\n"
            + "def species_trajectory(result, name: str) -> np.ndarray:\n"
            + '    """Return the time-series for ``name`` as a NumPy array.\n\n'
            + "    Raises KeyError if the species was not declared in the\n"
            + "    ModelSpec (carries `agent_error_patterns.md` \"Trusting an\n"
            + "    agent's I/O contract without checking the artifact\").\n"
            + '    """\n'
            + "    if name not in TRACKED_SPECIES:\n"
            + "        raise KeyError(\n"
            + '            f"Species {name!r} not in "\n'
            + '            f"TRACKED_SPECIES={TRACKED_SPECIES!r}"\n'
            + "        )\n"
            + "    series = result.diagnostics.get(name)\n"
            + "    if series is None:\n"
            + '        raise KeyError(f"Run did not emit a diagnostic for species {name!r}")\n'
            + "    return np.asarray(series)\n"
        )

    @staticmethod
    def _render_run_helper(spec: ModelSpec) -> str:
        return (
            _GENERATED_HEADER
            + '"""``python -m`` runnable for the validation runner.\n\n'
            + 'Calling ``run_capsule()`` builds the Experiment, runs it on the\n'
            + 'python_cpu backend, and returns ``(experiment, result)``.\n'
            + '"""\n\n'
            + "from __future__ import annotations\n\n"
            + "from .experiment import run as _run\n\n\n"
            + 'def run_capsule() -> "tuple[object, object]":\n'
            + "    return _run()\n"
        )

    @staticmethod
    def _render_readme(spec: ModelSpec) -> str:
        return (
            "# Generated experiment — "
            f"{spec.model.name}\n\n"
            f"- Domain: `{spec.model.domain}`\n"
            f"- Schema: `{spec.schema_version}`\n"
            f"- Species: {len(spec.species)}\n"
            f"- Interactions: {len(spec.interactions)}\n"
            f"- Equations: {len(spec.equations)}\n\n"
            "## Layout\n\n"
            "- `experiment.py` — Phase-1 `Experiment` + `Runner` driver.\n"
            "- `config.yaml` — Reviewer-editable runtime config.\n"
            "- `diagnostics.py` — Helpers for extracting time-series from a run.\n"
            "- `run.py` — `run_capsule()` entry point used by the Phase-6E "
            "validation runner.\n"
            "- `tests/` — Generated unit, dimensional, smoke, and regression "
            "tests (Phase 6C).\n"
            "- `codegen_manifest.json` — File hashes; consumed by the "
            "regeneration diff endpoint.\n\n"
            "## Editing\n\n"
            "This tree is regenerated whenever the ModelSpec changes. **Hand**\n"
            "**edits go in `../user_edits/`** — the code generator never\n"
            "overwrites that directory (Phase 6B sandbox).\n"
        )


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_under_path(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
    except ValueError:
        return False
    return True


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds")


# Re-export for convenience.
__all__ = [
    "CodeGenerationError",
    "CodeGenerationResult",
    "CodeGenerator",
    "Experiment",
    "RunConfig",
    "model_spec_to_dict",
]
