"""Phase 6C — Test Generation.

Plan §Phase 6 / 6C enumerates five task bullets:

  1. Generate unit tests.
  2. Generate dimensional tests.
  3. Generate smoke tests.
  4. Generate convergence tests if appropriate.
  5. Generate regression hooks.

Each becomes its own pytest file under
``<capsule>/src/generated/tests/``. The deterministic implementation
synthesizes a minimal but real test for each bullet from the
ModelSpec; reviewers extend in ``../user_edits/tests/``.

The convergence file is emitted only when the spec's geometry has
``dimensionality > 0`` — for a 0D rate-equation spec there's no grid
to converge on, so a stub there would be cargo-culting.
"""

from __future__ import annotations

from simworkbench.model_spec import ModelSpec


class TestGenerator:
    """Render generated pytest files for a ModelSpec."""

    def render(self, spec: ModelSpec) -> dict[str, str]:
        """Return ``{relative_path: file_body}`` for each generated test."""
        out: dict[str, str] = {
            "src/generated/tests/__init__.py": "",
            "src/generated/tests/test_unit.py": _render_unit(spec),
            "src/generated/tests/test_dimensional.py": _render_dimensional(spec),
            "src/generated/tests/test_smoke.py": _render_smoke(spec),
            "src/generated/tests/test_regression.py": _render_regression(spec),
        }
        if spec.geometry.dimensionality > 0:
            out["src/generated/tests/test_convergence.py"] = _render_convergence(spec)
        return out


_HEADER = (
    '"""Generated by simworkbench.codegen.TestGenerator.\n\n'
    "Hand-edits go in ../user_edits/tests/ — regeneration overwrites this\n"
    "file but never touches user_edits/.\n"
    '"""\n\n'
    "from __future__ import annotations\n\n"
)


def _render_unit(spec: ModelSpec) -> str:
    species_names = [s.name for s in spec.species] or ["A"]
    species_repr = repr(species_names)
    return (
        _HEADER
        + "from simworkbench.model_spec import load_yaml\n"
        + "from pathlib import Path\n\n\n"
        + "SPEC_PATH = Path(__file__).resolve().parents[3] / 'model' / 'model_spec.yaml'\n\n\n"
        + "def test_modelspec_loads():\n"
        + "    spec = load_yaml(SPEC_PATH)\n"
        + f"    assert spec.model.domain == {spec.model.domain!r}\n\n\n"
        + "def test_species_present():\n"
        + "    spec = load_yaml(SPEC_PATH)\n"
        + "    names = [s.name for s in spec.species]\n"
        + f"    assert names == {species_repr}\n"
    )


def _render_dimensional(spec: ModelSpec) -> str:
    return (
        _HEADER
        + "from simworkbench.model_spec import load_yaml\n"
        + "from simworkbench.units import Q\n"
        + "from pathlib import Path\n\n\n"
        + "SPEC_PATH = Path(__file__).resolve().parents[3] / 'model' / 'model_spec.yaml'\n\n\n"
        + "def test_initial_densities_are_number_density():\n"
        + '    """Every species\' initial_density must be dimensionally a number density."""\n'
        + "    spec = load_yaml(SPEC_PATH)\n"
        + '    expected = Q(1.0, "1/m^3").dimensionality\n'
        + "    for s in spec.species:\n"
        + "        assert s.initial_density.dimensionality == expected, (\n"
        + '            f"species {s.name!r} initial_density has wrong dimensionality"\n'
        + "        )\n"
    )


def _render_smoke(spec: ModelSpec) -> str:
    return (
        _HEADER
        + "from simworkbench.experiment import Experiment, RunConfig\n"
        + "from simworkbench.model_spec import load_yaml\n"
        + "from simworkbench.runtime import Runner\n"
        + "from pathlib import Path\n\n\n"
        + "SPEC_PATH = Path(__file__).resolve().parents[3] / 'model' / 'model_spec.yaml'\n\n\n"
        + "def test_runs_for_a_short_window():\n"
        + '    """Smoke: build the experiment and run it for ~10 ns."""\n'
        + "    spec = load_yaml(SPEC_PATH)\n"
        + "    experiment = Experiment.from_model_spec(\n"
        + "        spec,\n"
        + "        run_config=RunConfig(\n"
        + '            start_time="0 s", end_time="10 ns", max_steps=4, seed=0,\n'
        + "        ),\n"
        + "    )\n"
        + "    result = Runner(experiment, base_seed=0).run()\n"
        + "    assert result.diagnostics, 'no diagnostics emitted by smoke run'\n"
    )


def _render_regression(spec: ModelSpec) -> str:
    return (
        _HEADER
        + "import json\n"
        + "from pathlib import Path\n\n\n"
        + "REGRESSION_BASELINE = Path(__file__).resolve().parent / 'regression_baseline.json'\n\n\n"
        + "def test_regression_baseline_present_or_skipped():\n"
        + '    """Regression hook — once a baseline is recorded, the next run\n'
        + "    compares against it. Until then the test reports its absence so\n"
        + "    the reviewer remembers to record one.\n"
        + '    """\n'
        + "    if not REGRESSION_BASELINE.exists():\n"
        + "        import pytest\n"
        + "        pytest.skip('No regression baseline yet; record one and re-run.')\n"
        + "    baseline = json.loads(REGRESSION_BASELINE.read_text(encoding='utf-8'))\n"
        + "    assert isinstance(baseline, dict)\n"
    )


def _render_convergence(spec: ModelSpec) -> str:
    return (
        _HEADER
        + "import pytest\n\n\n"
        + "@pytest.mark.skip(\n"
        + "    reason=(\n"
        + '        "Convergence test reviewer-supplied: ModelSpec geometry is "\n'
        + '        f"non-zero ({0}D); record paper benchmark + grid sweep first."\n'
        + "    )\n"
        + ")\n"
        + "def test_grid_convergence():\n"
        + "    pass\n"
    )


__all__ = ["TestGenerator"]
