"""Phase 8 / 8E — Slurm batch-script generator.

Packages an ``Experiment`` into a deployable bundle an HPC user can
``sbatch <bundle>/submit.sh`` from a login node. The bundle is
self-contained for *the workbench's payload + entrypoint*; the
**remote node must already have ``simworkbench-core`` available** —
either installed (``pip install simworkbench-core``) or reachable via
``PYTHONPATH`` / ``SIMWORKBENCH_CORE_PATH`` to a checkout. The
generated ``run_remote.py`` walks both env vars and prepends them to
``sys.path`` before importing the workbench. The bundle does NOT
ship a wheel; that level of self-containment lands when an HPC
"deploy" script is added.

The bundle contains:

  - ``submit.sh`` — Slurm batch script with all directives.
  - ``experiment.yaml`` — the Experiment payload.
  - ``run_remote.py`` — the remote-node entry point. Reads the
    experiment, runs it on the local Phase-1 ``Runner``, writes
    ``result.json`` next to itself.

We don't talk to a real Slurm scheduler from this module — generating
the bundle and having ``run_remote.py`` work in isolation is the
contract. The Phase-8 gate-walk simulates the remote node by running
``run_remote.py`` as a subprocess locally with PYTHONPATH set.

Carries `agent_error_patterns.md` "Documentation claims behavior the
code can't deliver" forward (Phase-8 audit): the earlier docstring
called the bundle "self-contained" without qualification.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path

from simworkbench.experiment import Experiment
from simworkbench.paths import is_under_workbench

_RUN_REMOTE_TEMPLATE = textwrap.dedent('''\
    #!/usr/bin/env python3
    """run_remote.py — Phase 8 Slurm bundle entry point.

    Re-imports the workbench, runs the bundled experiment, and writes
    result.json next to this file. Generated by SlurmJob.write().
    """

    from __future__ import annotations

    import json
    import os
    import sys
    import traceback
    from pathlib import Path

    HERE = Path(__file__).resolve().parent


    def _ensure_workbench_on_path() -> None:
        # The bundle ships with the YAML payload; it does NOT bundle
        # the Python core. The remote node either has the workbench
        # installed (pip install simworkbench-core) or it sets
        # PYTHONPATH to point at a checkout. We support the second so
        # the gate-walk runs locally without needing a global install.
        for env_var in ("SIMWORKBENCH_CORE_PATH", "PYTHONPATH"):
            value = os.environ.get(env_var, "")
            for entry in value.split(os.pathsep):
                if entry and entry not in sys.path:
                    sys.path.insert(0, entry)


    def main() -> int:
        _ensure_workbench_on_path()
        try:
            from simworkbench.experiment import Experiment
            from simworkbench.runtime import Runner
        except ImportError as exc:
            (HERE / "result.json").write_text(
                json.dumps({"error": f"workbench import failed: {exc}"}),
                encoding="utf-8",
            )
            return 2

        experiment_path = HERE / "experiment.yaml"
        try:
            experiment = Experiment.load_yaml(experiment_path)
        except Exception as exc:  # noqa: BLE001
            (HERE / "result.json").write_text(
                json.dumps({"error": f"experiment load failed: {exc}"}),
                encoding="utf-8",
            )
            return 3
        try:
            result = Runner(experiment, base_seed=experiment.run_config.seed).run()
        except Exception as exc:  # noqa: BLE001
            (HERE / "result.json").write_text(
                json.dumps({
                    "error": f"runner failed: {type(exc).__name__}: {exc}",
                    "traceback": traceback.format_exc(),
                }),
                encoding="utf-8",
            )
            return 4

        payload = {
            "run_id": result.run_id,
            "state": result.state.value,
            "elapsed_seconds": result.elapsed_seconds,
            "final_simulation_time": result.final_simulation_time,
            "diagnostics": {k: list(v) for k, v in result.diagnostics.items()},
            "placeholders": list(result.placeholders),
            "backend": experiment.backend_config.name,
        }
        (HERE / "result.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
        return 0


    if __name__ == "__main__":
        sys.exit(main())
''')


@dataclass
class SlurmJob:
    """One Slurm submission packaged from an ``Experiment``."""

    experiment: Experiment
    partition: str
    time_limit: str
    nodes: int = 1
    ntasks: int = 1
    cpus_per_task: int = 1
    job_name: str | None = None
    extra_directives: tuple[str, ...] = ()
    extra_setup: str = ""
    notes: str = ""

    def write(
        self,
        target: str | Path,
        *,
        require_workbench_target: bool = True,
    ) -> Path:
        """Write the bundle to ``target`` (a directory). Returns its path.

        Default: ``target`` must lie under one of the four workbench-
        managed roots (``local_cache/``, ``temp_imports/``,
        ``temp_runs/``, ``simulation_capsules/``). The check mirrors
        the export pipeline so HPC bundles can't accidentally write
        to ``/private/tmp`` or arbitrary user directories. Pass
        ``require_workbench_target=False`` only when the user
        explicitly chose an external destination via the orchestrator
        UI / CLI flag.

        Carries `agent_error_patterns.md` "External-writer functions
        skip the locality guard that exporters got right" (Phase-8
        audit). Validates BEFORE creating the directory so a refused
        target leaves no trace on disk.
        """
        out = Path(target)
        if require_workbench_target and not is_under_workbench(out):
            raise PermissionError(
                f"Refusing to write Slurm bundle outside workbench-managed "
                f"roots: {out}. Allowed roots: local_cache/, temp_imports/, "
                "temp_runs/, simulation_capsules/. Pass "
                "require_workbench_target=False if the user explicitly "
                "chose an external destination."
            )
        out.mkdir(parents=True, exist_ok=True)

        # Experiment payload.
        self.experiment.save_yaml(out / "experiment.yaml")

        # run_remote.py entry point.
        run_remote = out / "run_remote.py"
        run_remote.write_text(_RUN_REMOTE_TEMPLATE, encoding="utf-8")
        run_remote.chmod(0o755)

        # submit.sh batch script.
        job_name = self.job_name or self.experiment.name
        directives = [
            f"#SBATCH --job-name={job_name}",
            f"#SBATCH --partition={self.partition}",
            f"#SBATCH --time={self.time_limit}",
            f"#SBATCH --nodes={self.nodes}",
            f"#SBATCH --ntasks={self.ntasks}",
            f"#SBATCH --cpus-per-task={self.cpus_per_task}",
            "#SBATCH --output=slurm-%j.out",
            "#SBATCH --error=slurm-%j.err",
        ]
        directives.extend(f"#SBATCH {d}" for d in self.extra_directives)

        body = (
            "#!/usr/bin/env bash\n"
            + "#\n"
            + "# Generated by simworkbench.hpc.SlurmJob.\n"
            + "# Submit with: sbatch submit.sh\n"
            + "#\n"
            + "\n".join(directives) + "\n\n"
            + "set -euo pipefail\n\n"
            + "BUNDLE_DIR=\"$( cd \"$( dirname \"${BASH_SOURCE[0]}\" )\" && pwd )\"\n"
            + "cd \"$BUNDLE_DIR\"\n\n"
            + (self.extra_setup + "\n\n" if self.extra_setup else "")
            + "python3 run_remote.py\n"
        )
        sbatch = out / "submit.sh"
        sbatch.write_text(body, encoding="utf-8")
        sbatch.chmod(0o755)

        # Notes file (optional, surfaces context for the reviewer).
        if self.notes:
            (out / "notes.md").write_text(
                f"# {job_name}\n\n{self.notes}\n", encoding="utf-8"
            )

        return out


__all__ = ["SlurmJob"]
