"""Phase 2C — Notebook exporter.

Generates a Jupyter notebook scaffold (``analysis.ipynb``) preconfigured to
load the capsule's diagnostics and plot a couple of series. Plain JSON —
no ``nbformat`` runtime dep.
"""

from __future__ import annotations

import json
from pathlib import Path

from simworkbench.paths import is_under_workbench

_NB_MINOR_VERSION = 5
_NB_MAJOR_VERSION = 4


def export_notebook(
    capsule_dir: str | Path,
    target: str | Path,
    *,
    notebook_name: str = "analysis.ipynb",
    require_workbench_target: bool = True,
) -> Path:
    """Write ``<target>/notebooks/<notebook_name>``. Returns the path.

    The notebook has three cells: a markdown header naming the capsule,
    a code cell that loads ``results/diagnostics.h5`` via h5py, and a code
    cell that plots a couple of series with matplotlib.
    """
    out_dir = Path(target) / "notebooks"
    if require_workbench_target and not is_under_workbench(out_dir):
        raise PermissionError(
            f"Refusing to write notebook outside workbench-managed roots: {out_dir}"
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = out_dir / notebook_name

    capsule_name = Path(capsule_dir).name
    header_md = (
        f"# Analysis: {capsule_name}\n\n"
        "This notebook was generated by `simworkbench.serialization.exporters."
        "notebook`.\n\n"
        "It loads the capsule's `results/diagnostics.h5` and plots a couple of "
        "series. Run all cells to reproduce the figures.\n\n"
        "Paths are resolved relative to this notebook so the export remains "
        "portable across machines: by default the notebook lives at "
        f"`<export>/notebooks/{notebook_name}` and finds the capsule's "
        "results at `../results/diagnostics.h5`. Override `CAPSULE_RESULTS` "
        "below if you've moved the file.\n"
    )
    load_code = (
        "from pathlib import Path\n"
        "import h5py\n"
        "\n"
        "# Path is relative to this notebook so the export is portable across\n"
        "# machines (carries agent_error_patterns.md 'Embedding absolute paths\n"
        "# in exported artifacts'). Override to point at the capsule wherever\n"
        "# you placed it.\n"
        "CAPSULE_RESULTS = Path('..') / 'results'\n"
        "\n"
        "diagnostics = {}\n"
        "with h5py.File(CAPSULE_RESULTS / 'diagnostics.h5', 'r') as fh:\n"
        "    for name in fh:\n"
        "        diagnostics[name] = fh[name][...]\n"
        "list(diagnostics)\n"
    )
    plot_code = (
        "import matplotlib.pyplot as plt\n"
        "\n"
        "t = diagnostics['time_seconds']\n"
        "fig, ax = plt.subplots(figsize=(7, 4))\n"
        "for name, series in diagnostics.items():\n"
        "    if name == 'time_seconds':\n"
        "        continue\n"
        "    ax.plot(t, series, label=name)\n"
        "ax.set_xlabel('time (s)')\n"
        "ax.legend()\n"
        "fig.tight_layout()\n"
        "fig\n"
    )

    notebook = {
        "cells": [
            _markdown_cell(header_md),
            _code_cell(load_code),
            _code_cell(plot_code),
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
            "simworkbench": {
                "capsule_name": capsule_name,
                "exporter": "simworkbench.serialization.exporters.notebook",
            },
        },
        "nbformat": _NB_MAJOR_VERSION,
        "nbformat_minor": _NB_MINOR_VERSION,
    }

    notebook_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
    return notebook_path


def _markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": _split_lines_keep_newlines(source),
    }


def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _split_lines_keep_newlines(source),
    }


def _split_lines_keep_newlines(source: str) -> list[str]:
    """Notebook spec wants ``source`` as a list of lines including their
    trailing newlines (last line may omit it). Mirror that."""
    parts = source.splitlines(keepends=True)
    return parts


__all__ = ["export_notebook"]
